server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userCircuitBreaker
                fallbackUri: forward:/fallback

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notify/**
          filters:
            - name: CircuitBreaker
              args:
                name: notifyCircuitBreaker
                fallbackUri: forward:/fallback
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
